### ISSUE TITLE
Add support for null checks

### ISSUE THREAD

**Issue by marc-antoine-girard** [Thundernerd/Unity3D-SerializableInterface#33]
Considering this Code:
```csharp
public interface IDog { }
[ExecuteAlways]
public class CodeExample : MonoBehaviour, IDog
{
    public SerializableInterface<IDog> MyVariable;

    private void Update()
    {
        Debug.Log( $"{MyVariable.Value == null} {ReferenceEquals(MyVariable.Value, null)} {(Object)MyVariable.Value == null}");
    }
}
```

1. Add CodeExample on a GameObject (1) and another GameObject (2)
2. Reference CodeExample from GameObject (2) in CodeExample on GameObject (1)
3. Then delete GameObject (2)

Output in Console: "False, False, True". 

The third value is the expected behaviour, since the referenced Component has been destroyed. This happens because, by default, we're not using Unity's equality operator. 

A clean way to handle this would be to add this method in SerializableInterface:
```csharp
public bool IsValueNull() => Value == null || Value.Equals(null);
```
or 
```csharp
// which is a code that can actually be found in the Visual Scripting package - ish
// Unity.VisualScripting.UnityObjectUtility.IsUnityNull
public bool IsValueNull() => Value == null || (Value is UnityEngine.Object obj && obj == null);
```

Now with the following code, doing the same steps:
```csharp
public interface IDog { }

[ExecuteAlways]
public class CodeExample : MonoBehaviour, IDog
{
    public SerializableInterface<IDog> MyVariable;

    private void Update()
    {
        Debug.Log( $"{MyVariable.IsValueNull()} {ReferenceEquals(MyVariable.Value, null)} {(Object)MyVariable.Value == null}");
    }
}
```
Outputs: "True, False, True"

## Relevant articles
https://sometimesicode.wordpress.com/2020/04/01/null-check-and-equality-in-unity/
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5981#issuecomment-571914943

**Comment by marc-antoine-girard** [comment]
There's also the question of "Should we consider SerializableInterface as a practical wrapper or an unfortunate necessity?", meaning, should we allow to simply do null check on the object itself, which would do the null check to its object internally, like so:
```csharp
if(MyVariable == null)
```
Which would mean "Is MyVariable null (usually not, since always serialized), if not, is the Value null?"
This implementation would require adding `operator==`, `operator!=`, and if we want to copy Unity's behaviour, `operator bool`.
What's your take on that @Thundernerd ?

**Comment by Thundernerd** [comment]
To answer your first question, I think this is an unfortunate necessity.
I think it wouldn't be a bad thing to implement both options, so a `.HasValue` and adding the operators :)

**Comment by Thundernerd** [comment]
After careful consideration I have decided against implementing the operators, for now. I have added two (functionally) the same extension methods that allow convenient access to a value if it has been defined using `TryGetValue(out value);` or `IsDefined(out value);`
