### ISSUE TITLE
Cannot select ScriptableObject in built-in picker for SerializableInterface reference

### ISSUE THREAD

**Issue by sandsalamand** [Thundernerd/Unity3D-SerializableInterface#58]
**Describe the bug**
When editing an object stored in a SerializableInterface reference, I can manually drag in a reference to a ScriptableObject, but I can't select one using the built-in picker. None of my ScriptableObjects show up in the picker.

**To Reproduce**

Add a SerializableInterface field to a MonoBehaviour, then select a class with a reference to a ScriptableObject. Then click the circle on the right of the inspector field to select a ScriptableObject.

`[SerializeField] private SerializableInterface<IInteraction> interaction;`

```
[Serializable]
public class DisableHouseLights : IInteraction
{
	public AudioClipReference powerDownClip;
}
```

**Expected behavior**
The picker should allow me to select any AudioClipReference in my project.

**Screenshots**
![image](https://github.com/Thundernerd/Unity3D-SerializableInterface/assets/38278077/98e7a90d-c8f6-4bdc-b74c-0ca18e76be79)
![image](https://github.com/Thundernerd/Unity3D-SerializableInterface/assets/38278077/bc158f4f-4ce6-4160-a4a2-78fc3830086c)

**Desktop (please complete the following information):**
Windows 10

**Unity (please complete the following information):**
2022.2.11f1

**Additional context**
N/A

**Comment by Thundernerd** [comment]
I've finally gotten around to doing some investigation on the issues and I'm starting to lean towards submitting a bug report to Unity.

I'm not sure when it happened but somewhere after 2021.3 something is happening with the custom property drawers and indentation. It is very weird and I cannot seem to figure out why my custom property drawer is being handed very weirdly offset rectangles for drawing.

I'm going to do a bit more investigating with different Unity 2022 versions as I've only tried 2022.3 but I'm suspecting there might be a deeper issue within Unity!

**Comment by Thundernerd** [comment]
I got around to fixing some of the issues that I was experiencing with Unity 2022, however, I wasn't able to reproduce this issue.

Do you perhaps have a test project?

**Comment by sandsalamand** [comment]
I wasn't able to reproduce this in a clean test project, even after adding all the Editor scripts from my bugged project. Sorry for the false alarm; hopefully you were able to fix some of those other issues you mentioned.
