### ISSUE TITLE
Instantiating Objects with interface

### ISSUE THREAD

**Issue by sima995** [Thundernerd/Unity3D-SerializableInterface#60]
**Is your feature request related to a problem? Please describe.**
Referencing `UnityEngine.Object` with a specific interface is great, but then trying to instantiating them is unsafe. A cast is required at some point.

**Describe the solution you'd like**
A reference type where only classes of type `UnityEngine.Object` are allowed. Getting the value of that reference would always return that type so `Instantiate(referencedPrefab.Value)` would work straight away.

Maybe an extension method that instantiates the Object and returns the interface?

**Comment by Thundernerd** [comment]
Fixed in #61
